"""Fixtures pour les tests lectura-correcteur.

Fournit un MockLexique satisfaisant LexiqueProtocol pour les tests
unitaires qui n'ont pas besoin du vrai lexique SQLite.
"""

from __future__ import annotations

from typing import Any

import pytest


class MockLexique:
    """Lexique minimal pour les tests unitaires."""

    def __init__(
        self,
        formes: dict[str, list[dict[str, Any]]] | None = None,
        conjugaisons: dict[str, dict] | None = None,
    ):
        if formes is None:
            formes = _DONNEES_DEFAUT()
        if conjugaisons is None:
            conjugaisons = _CONJUGAISONS_DEFAUT()
        self._formes = formes
        self._formes_set = frozenset(formes.keys())
        self._conjugaisons = conjugaisons

    def existe(self, mot: str) -> bool:
        return mot.lower() in self._formes_set

    def info(self, mot: str) -> list[dict[str, Any]]:
        return self._formes.get(mot.lower(), [])

    def frequence(self, mot: str) -> float:
        entries = self._formes.get(mot.lower(), [])
        if not entries:
            return 0.0
        return max(float(e.get("freq", 0.0)) for e in entries)

    def phone_de(self, mot: str) -> str | None:
        entries = self._formes.get(mot.lower(), [])
        phones = [
            (e.get("phone", ""), float(e.get("freq", 0.0)))
            for e in entries
            if e.get("phone")
        ]
        if not phones:
            return None
        phones.sort(key=lambda x: -x[1])
        return phones[0][0]

    def homophones(self, phone: str) -> list[dict[str, Any]]:
        results = []
        for entries in self._formes.values():
            for e in entries:
                if e.get("phone") == phone:
                    results.append(e)
        return results

    def conjuguer(self, verbe: str) -> dict[str, dict[str, dict[str, str]]]:
        """Retourne un dict {mode: {temps: {personne: forme}}}."""
        return self._conjugaisons.get(verbe.lower(), {})

    def lemme_de(self, mot: str) -> str | None:
        """Retourne le lemme le plus frequent pour un mot."""
        entries = self._formes.get(mot.lower(), [])
        if not entries:
            return None
        # Prendre le lemme de l'entree la plus frequente
        best = max(entries, key=lambda e: float(e.get("freq", 0)))
        return best.get("lemme", best.get("ortho", "")).lower()

    def formes_de(self, lemme: str) -> list[dict[str, Any]]:
        """Retourne toutes les formes associees a un lemme."""
        results = []
        for entries in self._formes.values():
            for e in entries:
                if e.get("lemme", e.get("ortho", "")).lower() == lemme.lower():
                    results.append(e)
        return results

    def verbes_par_phone_et_personne(
        self, phones: list[str], personne: str, nombre: str,
    ) -> list[dict[str, Any]]:
        """Stub pour la recherche phonetique de verbes conjugues."""
        return []

    def close(self) -> None:
        pass


def _DONNEES_DEFAUT() -> dict[str, list[dict[str, Any]]]:
    """Jeu de donnees par defaut pour les tests."""
    return {
        "chat": [{"ortho": "chat", "cgram": "NOM", "phone": "\u0283a",
                   "freq": 45.2, "genre": "m", "nombre": "s"}],
        "chats": [{"ortho": "chats", "cgram": "NOM", "phone": "\u0283a",
                    "freq": 12.1, "genre": "m", "nombre": "p"}],
        "maison": [{"ortho": "maison", "cgram": "NOM", "phone": "m\u025bz\u0254\u0303",
                     "freq": 38.7, "genre": "f", "nombre": "s"}],
        "maisons": [{"ortho": "maisons", "cgram": "NOM", "phone": "m\u025bz\u0254\u0303",
                      "freq": 8.2, "genre": "f", "nombre": "p"}],
        "mange": [{"ortho": "mange", "cgram": "VER", "phone": "m\u0251\u0303\u0292",
                    "freq": 15.4, "personne": "3", "nombre": "s", "lemme": "manger"}],
        "manges": [{"ortho": "manges", "cgram": "VER", "phone": "m\u0251\u0303\u0292",
                     "freq": 3.2, "personne": "2", "nombre": "s", "lemme": "manger"}],
        "mangent": [{"ortho": "mangent", "cgram": "VER", "phone": "m\u0251\u0303\u0292",
                      "freq": 5.1, "personne": "3", "nombre": "p", "lemme": "manger"}],
        "enfant": [{"ortho": "enfant", "cgram": "NOM", "phone": "\u0251\u0303f\u0251\u0303",
                     "freq": 30.0, "genre": "m", "nombre": "s"}],
        "enfants": [{"ortho": "enfants", "cgram": "NOM", "phone": "\u0251\u0303f\u0251\u0303",
                      "freq": 20.0, "genre": "m", "nombre": "p"}],
        "pomme": [{"ortho": "pomme", "cgram": "NOM", "phone": "p\u0254m",
                    "freq": 5.0, "genre": "f", "nombre": "s"}],
        "pommes": [{"ortho": "pommes", "cgram": "NOM", "phone": "p\u0254m",
                     "freq": 3.0, "genre": "f", "nombre": "p"}],
        "le": [{"ortho": "le", "cgram": "ART:def", "phone": "l\u0259",
                 "freq": 890.5, "genre": "m", "nombre": "s"}],
        "la": [{"ortho": "la", "cgram": "ART:def", "phone": "la",
                 "freq": 720.3, "genre": "f", "nombre": "s"}],
        "les": [{"ortho": "les", "cgram": "ART:def", "phone": "le",
                  "freq": 650.1, "nombre": "p"}],
        "des": [{"ortho": "des", "cgram": "ART:ind", "phone": "de",
                  "freq": 400.2, "nombre": "p"}],
        "est": [{"ortho": "est", "cgram": "AUX", "phone": "\u025b",
                  "freq": 500.0, "personne": "3", "nombre": "s"}],
        "et": [{"ortho": "et", "cgram": "CON", "phone": "e",
                 "freq": 450.0}],
        "son": [{"ortho": "son", "cgram": "ADJ:pos", "phone": "s\u0254\u0303",
                  "freq": 120.0, "genre": "m", "nombre": "s"}],
        "il": [{"ortho": "il", "cgram": "PRO:per", "phone": "il",
                 "freq": 800.0, "personne": "3", "nombre": "s"}],
        "ils": [{"ortho": "ils", "cgram": "PRO:per", "phone": "il",
                  "freq": 300.0, "personne": "3", "nombre": "p"}],
        "elle": [{"ortho": "elle", "cgram": "PRO:per", "phone": "\u025bl",
                   "freq": 600.0, "personne": "3", "nombre": "s"}],
        "elles": [{"ortho": "elles", "cgram": "PRO:per", "phone": "\u025bl",
                    "freq": 150.0, "personne": "3", "nombre": "p"}],
        "tu": [{"ortho": "tu", "cgram": "PRO:per", "phone": "ty",
                 "freq": 500.0, "personne": "2", "nombre": "s"}],
        "je": [{"ortho": "je", "cgram": "PRO:per", "phone": "\u0292\u0259",
                 "freq": 700.0, "personne": "1", "nombre": "s"}],
        "dan": [{"ortho": "dan", "cgram": "NOM", "phone": "dɑ̃",
                 "freq": 0.1}],
        "dans": [{"ortho": "dans", "cgram": "PRE", "phone": "d\u0251\u0303",
                   "freq": 150.0}],
        "belle": [{"ortho": "belle", "cgram": "ADJ", "phone": "b\u025bl",
                    "freq": 50.0, "genre": "f", "nombre": "s"}],
        "arrive": [{"ortho": "arrive", "cgram": "VER", "phone": "a\u0281iv",
                     "freq": 478.0, "personne": "3", "nombre": "s"}],
        "bonjour": [{"ortho": "bonjour", "cgram": "NOM", "phone": "b\u0254\u0303\u0292u\u0281",
                      "freq": 60.0}],
        "comment": [{"ortho": "comment", "cgram": "ADV", "phone": "k\u0254m\u0251\u0303",
                      "freq": 100.0}],
        "jouent": [{"ortho": "jouent", "cgram": "VER", "phone": "\u0292u",
                     "freq": 10.0, "personne": "3", "nombre": "p"}],
        "dort": [{"ortho": "dort", "cgram": "VER", "phone": "d\u0254\u0281",
                   "freq": 15.0, "personne": "3", "nombre": "s"}],
        "dorment": [{"ortho": "dorment", "cgram": "VER", "phone": "d\u0254\u0281m",
                      "freq": 8.0, "personne": "3", "nombre": "p"}],
        "droit": [{"ortho": "droit", "cgram": "ADJ", "phone": "d\u0281wa",
                    "freq": 40.0, "genre": "m", "nombre": "s"}],
        "finit": [{"ortho": "finit", "cgram": "VER", "phone": "fini",
                    "freq": 12.0, "personne": "3", "nombre": "s"}],
        "finissent": [{"ortho": "finissent", "cgram": "VER", "phone": "finis",
                        "freq": 4.0, "personne": "3", "nombre": "p"}],
        "prend": [{"ortho": "prend", "cgram": "VER", "phone": "p\u0281\u0251\u0303",
                    "freq": 18.0, "personne": "3", "nombre": "s"}],
        "prennent": [{"ortho": "prennent", "cgram": "VER", "phone": "p\u0281\u025bn",
                       "freq": 6.0, "personne": "3", "nombre": "p"}],
        "partent": [{"ortho": "partent", "cgram": "VER", "phone": "pa\u0281t",
                      "freq": 5.0, "personne": "3", "nombre": "p"}],
        "content": [{"ortho": "content", "cgram": "ADJ", "phone": "k\u0254\u0303t\u0251\u0303",
                      "freq": 20.0, "genre": "m", "nombre": "s"}],
        "contents": [{"ortho": "contents", "cgram": "ADJ", "phone": "k\u0254\u0303t\u0251\u0303",
                       "freq": 7.0, "genre": "m", "nombre": "p"}],
        "blanche": [{"ortho": "blanche", "cgram": "ADJ", "phone": "bl\u0251\u0303\u0283",
                      "freq": 15.0, "genre": "f", "nombre": "s"}],
        "blanches": [{"ortho": "blanches", "cgram": "ADJ", "phone": "bl\u0251\u0303\u0283",
                       "freq": 5.0, "genre": "f", "nombre": "p"}],
        "belles": [{"ortho": "belles", "cgram": "ADJ", "phone": "b\u025bl",
                     "freq": 12.0, "genre": "f", "nombre": "p"}],
        "grand": [{"ortho": "grand", "cgram": "ADJ", "phone": "g\u0281\u0251\u0303",
                    "freq": 40.0, "genre": "m", "nombre": "s"}],
        "grands": [{"ortho": "grands", "cgram": "ADJ", "phone": "g\u0281\u0251\u0303",
                     "freq": 15.0, "genre": "m", "nombre": "p"}],
        "grandes": [{"ortho": "grandes", "cgram": "ADJ", "phone": "g\u0281\u0251\u0303d",
                      "freq": 10.0, "genre": "f", "nombre": "p"}],
        "bien": [{"ortho": "bien", "cgram": "ADV", "phone": "bj\u025b\u0303",
                   "freq": 100.0}],
        "sont": [{"ortho": "sont", "cgram": "AUX", "phone": "s\u0254\u0303",
                   "freq": 200.0, "personne": "3", "nombre": "p"}],
        "chose": [{"ortho": "chose", "cgram": "NOM", "phone": "\u0283oz",
                    "freq": 50.0, "nombre": "s"}],
        # Verbes irreguliers (axe 3)
        "va": [{"ortho": "va", "cgram": "VER", "phone": "va",
                "freq": 80.0, "personne": "3", "nombre": "s"}],
        "vont": [{"ortho": "vont", "cgram": "VER", "phone": "v\u0254\u0303",
                  "freq": 30.0, "personne": "3", "nombre": "p"}],
        "fait": [{"ortho": "fait", "cgram": "VER", "phone": "f\u025b",
                  "freq": 60.0, "personne": "3", "nombre": "s"}],
        "font": [{"ortho": "font", "cgram": "VER", "phone": "f\u0254\u0303",
                  "freq": 20.0, "personne": "3", "nombre": "p"}],
        "dit": [{"ortho": "dit", "cgram": "VER", "phone": "di",
                 "freq": 50.0, "personne": "3", "nombre": "s"}],
        "disent": [{"ortho": "disent", "cgram": "VER", "phone": "diz",
                    "freq": 15.0, "personne": "3", "nombre": "p"}],
        "veut": [{"ortho": "veut", "cgram": "VER", "phone": "v\u00f8",
                  "freq": 40.0, "personne": "3", "nombre": "s"}],
        "veulent": [{"ortho": "veulent", "cgram": "VER", "phone": "v\u00f8l",
                     "freq": 12.0, "personne": "3", "nombre": "p"}],
        "voit": [{"ortho": "voit", "cgram": "VER", "phone": "vwa",
                  "freq": 35.0, "personne": "3", "nombre": "s"}],
        "voient": [{"ortho": "voient", "cgram": "VER", "phone": "vwa",
                    "freq": 10.0, "personne": "3", "nombre": "p"}],
        # Genre (axe 4)
        "petit": [{"ortho": "petit", "cgram": "ADJ", "phone": "p\u0259ti",
                   "freq": 60.0, "genre": "m", "nombre": "s"}],
        "petite": [{"ortho": "petite", "cgram": "ADJ", "phone": "p\u0259tit",
                    "freq": 40.0, "genre": "f", "nombre": "s"}],
        "petits": [{"ortho": "petits", "cgram": "ADJ", "phone": "p\u0259ti",
                    "freq": 20.0, "genre": "m", "nombre": "p"}],
        "petites": [{"ortho": "petites", "cgram": "ADJ", "phone": "p\u0259tit",
                     "freq": 15.0, "genre": "f", "nombre": "p"}],
        "grande": [{"ortho": "grande", "cgram": "ADJ", "phone": "g\u0281\u0251\u0303d",
                    "freq": 30.0, "genre": "f", "nombre": "s"}],
        "fille": [{"ortho": "fille", "cgram": "NOM", "phone": "fij",
                   "freq": 55.0, "genre": "f", "nombre": "s"}],
        "filles": [{"ortho": "filles", "cgram": "NOM", "phone": "fij",
                    "freq": 25.0, "genre": "f", "nombre": "p"}],
        # Accord a distance (axe 5)
        "voisine": [{"ortho": "voisine", "cgram": "NOM", "phone": "vwazin",
                     "freq": 15.0, "genre": "f", "nombre": "s"}],
        "de": [{"ortho": "de", "cgram": "PRE", "phone": "d\u0259",
                "freq": 500.0}],
        "une": [{"ortho": "une", "cgram": "ART:ind", "phone": "yn",
                 "freq": 400.0, "genre": "f", "nombre": "s"}],
        # Conjugaison P1p/P2p
        "nous": [{"ortho": "nous", "cgram": "PRO:per", "phone": "nu",
                  "freq": 300.0, "personne": "1", "nombre": "p"}],
        "vous": [{"ortho": "vous", "cgram": "PRO:per", "phone": "vu",
                  "freq": 300.0, "personne": "2", "nombre": "p"}],
        "mangeons": [{"ortho": "mangeons", "cgram": "VER", "phone": "m\u0251\u0303\u0292\u0254\u0303",
                      "freq": 3.0, "personne": "1", "nombre": "p"}],
        "mangez": [{"ortho": "mangez", "cgram": "VER", "phone": "m\u0251\u0303\u0292e",
                    "freq": 3.0, "personne": "2", "nombre": "p"}],
        "chante": [{"ortho": "chante", "cgram": "VER", "phone": "\u0283\u0251\u0303t",
                    "freq": 10.0, "personne": "3", "nombre": "s"}],
        "chantes": [{"ortho": "chantes", "cgram": "VER", "phone": "\u0283\u0251\u0303t",
                     "freq": 3.0, "personne": "2", "nombre": "s"}],
        "chantent": [{"ortho": "chantent", "cgram": "VER", "phone": "\u0283\u0251\u0303t",
                      "freq": 5.0, "personne": "3", "nombre": "p"}],
        "chantons": [{"ortho": "chantons", "cgram": "VER", "phone": "\u0283\u0251\u0303t\u0254\u0303",
                      "freq": 2.0, "personne": "1", "nombre": "p"}],
        "chantez": [{"ortho": "chantez", "cgram": "VER", "phone": "\u0283\u0251\u0303te",
                     "freq": 2.0, "personne": "2", "nombre": "p"}],
        # Participes passes
        "mangé": [{"ortho": "mangé", "cgram": "VER", "phone": "m\u0251\u0303\u0292e",
                   "freq": 8.0, "personne": "3", "nombre": "s", "lemme": "manger"}],
        "chanté": [{"ortho": "chanté", "cgram": "VER", "phone": "\u0283\u0251\u0303te",
                    "freq": 5.0}],
        "joué": [{"ortho": "joué", "cgram": "VER", "phone": "\u0292we",
                  "freq": 5.0}],
        "parlé": [{"ortho": "parlé", "cgram": "VER", "phone": "pa\u0281le",
                   "freq": 5.0}],
        "donné": [{"ortho": "donné", "cgram": "VER", "phone": "d\u0254ne",
                   "freq": 5.0}],
        # Infinitifs
        "manger": [{"ortho": "manger", "cgram": "VER", "phone": "m\u0251\u0303\u0292e",
                    "freq": 20.0, "mode": "inf", "lemme": "manger"}],
        "chanter": [{"ortho": "chanter", "cgram": "VER", "phone": "\u0283\u0251\u0303te",
                     "freq": 15.0, "mode": "inf"}],
        "jouer": [{"ortho": "jouer", "cgram": "VER", "phone": "\u0292we",
                   "freq": 15.0, "mode": "inf"}],
        "parler": [{"ortho": "parler", "cgram": "VER", "phone": "pa\u0281le",
                    "freq": 15.0, "mode": "inf"}],
        "donner": [{"ortho": "donner", "cgram": "VER", "phone": "d\u0254ne",
                    "freq": 15.0, "mode": "inf"}],
        # Auxiliaires
        "a": [{"ortho": "a", "cgram": "AUX", "phone": "a",
               "freq": 400.0, "personne": "3", "nombre": "s"}],
        "ai": [{"ortho": "ai", "cgram": "AUX", "phone": "e",
                "freq": 200.0, "personne": "1", "nombre": "s"}],
        "avons": [{"ortho": "avons", "cgram": "AUX", "phone": "av\u0254\u0303",
                   "freq": 50.0, "personne": "1", "nombre": "p"}],
        "avez": [{"ortho": "avez", "cgram": "AUX", "phone": "ave",
                  "freq": 50.0, "personne": "2", "nombre": "p"}],
        "ont": [{"ortho": "ont", "cgram": "AUX", "phone": "\u0254\u0303",
                 "freq": 100.0, "personne": "3", "nombre": "p"}],
        "suis": [{"ortho": "suis", "cgram": "AUX", "phone": "s\u0265i",
                  "freq": 200.0, "personne": "1", "nombre": "s"}],
        "sommes": [{"ortho": "sommes", "cgram": "AUX", "phone": "s\u0254m",
                    "freq": 50.0, "personne": "1", "nombre": "p"}],
        "êtes": [{"ortho": "êtes", "cgram": "AUX", "phone": "\u025bt",
                  "freq": 50.0, "personne": "2", "nombre": "p"}],
        # Negation
        "ne": [{"ortho": "ne", "cgram": "ADV", "phone": "n\u0259",
                "freq": 300.0}],
        "pas": [{"ortho": "pas", "cgram": "ADV", "phone": "pa",
                 "freq": 300.0}],
        # Prepositions/contractions
        "du": [{"ortho": "du", "cgram": "ART:def", "phone": "dy",
                "freq": 300.0, "genre": "m", "nombre": "s"}],
        "au": [{"ortho": "au", "cgram": "ART:def", "phone": "o",
                "freq": 250.0, "genre": "m", "nombre": "s"}],
        # ADJ genre supplementaires
        "gros": [{"ortho": "gros", "cgram": "ADJ", "phone": "g\u0281o",
                  "freq": 30.0, "genre": "m", "nombre": "s"}],
        "grosse": [{"ortho": "grosse", "cgram": "ADJ", "phone": "g\u0281os",
                    "freq": 20.0, "genre": "f", "nombre": "s"}],
        "grosses": [{"ortho": "grosses", "cgram": "ADJ", "phone": "g\u0281os",
                     "freq": 10.0, "genre": "f", "nombre": "p"}],
        "vert": [{"ortho": "vert", "cgram": "ADJ", "phone": "v\u025b\u0281",
                  "freq": 20.0, "genre": "m", "nombre": "s"}],
        "verte": [{"ortho": "verte", "cgram": "ADJ", "phone": "v\u025b\u0281t",
                   "freq": 15.0, "genre": "f", "nombre": "s"}],
        "verts": [{"ortho": "verts", "cgram": "ADJ", "phone": "v\u025b\u0281",
                   "freq": 8.0, "genre": "m", "nombre": "p"}],
        "vertes": [{"ortho": "vertes", "cgram": "ADJ", "phone": "v\u025b\u0281t",
                    "freq": 5.0, "genre": "f", "nombre": "p"}],
        # NOM supplementaires
        "voiture": [{"ortho": "voiture", "cgram": "NOM", "phone": "vwaty\u0281",
                     "freq": 30.0, "genre": "f", "nombre": "s"}],
        "voitures": [{"ortho": "voitures", "cgram": "NOM", "phone": "vwaty\u0281",
                      "freq": 15.0, "genre": "f", "nombre": "p"}],
        "jardin": [{"ortho": "jardin", "cgram": "NOM", "phone": "\u0292a\u0281d\u025b\u0303",
                    "freq": 20.0, "genre": "m", "nombre": "s"}],
        # Formes supplementaires pour les tests
        "un": [{"ortho": "un", "cgram": "ART:ind", "phone": "\u0153\u0303",
                "freq": 500.0, "genre": "m", "nombre": "s"}],
        "femme": [{"ortho": "femme", "cgram": "NOM", "phone": "fam",
                   "freq": 60.0, "genre": "f", "nombre": "s"}],
        "femmes": [{"ortho": "femmes", "cgram": "NOM", "phone": "fam",
                    "freq": 25.0, "genre": "f", "nombre": "p"}],
        "noir": [{"ortho": "noir", "cgram": "ADJ", "phone": "nwa\u0281",
                  "freq": 30.0, "genre": "m", "nombre": "s"}],
        "noire": [{"ortho": "noire", "cgram": "ADJ", "phone": "nwa\u0281",
                   "freq": 20.0, "genre": "f", "nombre": "s"}],
        "noirs": [{"ortho": "noirs", "cgram": "ADJ", "phone": "nwa\u0281",
                   "freq": 10.0, "genre": "m", "nombre": "p"}],
        "noires": [{"ortho": "noires", "cgram": "ADJ", "phone": "nwa\u0281",
                    "freq": 5.0, "genre": "f", "nombre": "p"}],
        "voisin": [{"ortho": "voisin", "cgram": "NOM", "phone": "vwaz\u025b\u0303",
                    "freq": 20.0, "genre": "m", "nombre": "s"}],
        "voisins": [{"ortho": "voisins", "cgram": "NOM", "phone": "vwaz\u025b\u0303",
                     "freq": 10.0, "genre": "m", "nombre": "p"}],
        "mes": [{"ortho": "mes", "cgram": "ADJ:pos", "phone": "me",
                 "freq": 150.0, "nombre": "p"}],
        "vas": [{"ortho": "vas", "cgram": "VER", "phone": "va",
                 "freq": 20.0, "personne": "2", "nombre": "s"}],
        "directeur": [{"ortho": "directeur", "cgram": "NOM", "phone": "diʁɛktœʁ",
                       "freq": 25.0, "genre": "m", "nombre": "s"}],
        "ecoles": [{"ortho": "ecoles", "cgram": "NOM", "phone": "ekɔl",
                    "freq": 10.0, "genre": "f", "nombre": "p"}],
        "visite": [{"ortho": "visite", "cgram": "VER", "phone": "vizit",
                    "freq": 10.0, "personne": "3", "nombre": "s"}],
        "visitent": [{"ortho": "visitent", "cgram": "VER", "phone": "vizit",
                      "freq": 5.0, "personne": "3", "nombre": "p"}],
        "rue": [{"ortho": "rue", "cgram": "NOM", "phone": "\u0281y",
                 "freq": 40.0, "genre": "f", "nombre": "s"}],
        "rues": [{"ortho": "rues", "cgram": "NOM", "phone": "\u0281y",
                  "freq": 15.0, "genre": "f", "nombre": "p"}],
        "livre": [{"ortho": "livre", "cgram": "NOM", "phone": "liv\u0281",
                   "freq": 35.0, "genre": "m", "nombre": "s"}],
        "livres": [{"ortho": "livres", "cgram": "NOM", "phone": "liv\u0281",
                    "freq": 15.0, "genre": "m", "nombre": "p"}],
        "ce": [{"ortho": "ce", "cgram": "DET:dem", "phone": "s\u0259",
                "freq": 200.0, "genre": "m", "nombre": "s"}],
        "cette": [{"ortho": "cette", "cgram": "DET:dem", "phone": "s\u025bt",
                   "freq": 150.0, "genre": "f", "nombre": "s"}],
        # Participes passes irreguliers
        "faire": [{"ortho": "faire", "cgram": "VER", "phone": "f\u025b\u0281",
                   "freq": 80.0, "mode": "inf"}],
        "fait": [{"ortho": "fait", "cgram": "VER", "phone": "f\u025b",
                  "freq": 60.0, "personne": "3", "nombre": "s"},
                 {"ortho": "fait", "cgram": "VER", "phone": "f\u025b",
                  "freq": 40.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "prendre": [{"ortho": "prendre", "cgram": "VER", "phone": "p\u0281\u0251\u0303d\u0281",
                     "freq": 50.0, "mode": "inf"}],
        "pris": [{"ortho": "pris", "cgram": "VER", "phone": "p\u0281i",
                  "freq": 30.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "voir": [{"ortho": "voir", "cgram": "VER", "phone": "vwa\u0281",
                  "freq": 60.0, "mode": "inf"}],
        "vu": [{"ortho": "vu", "cgram": "VER", "phone": "vy",
                "freq": 30.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "dire": [{"ortho": "dire", "cgram": "VER", "phone": "di\u0281",
                  "freq": 50.0, "mode": "inf"}],
        "écrire": [{"ortho": "écrire", "cgram": "VER", "phone": "ek\u0281i\u0281",
                    "freq": 30.0, "mode": "inf"}],
        "écrit": [{"ortho": "écrit", "cgram": "VER", "phone": "ek\u0281i",
                   "freq": 20.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "mettre": [{"ortho": "mettre", "cgram": "VER", "phone": "m\u025bt\u0281",
                    "freq": 40.0, "mode": "inf"}],
        "mis": [{"ortho": "mis", "cgram": "VER", "phone": "mi",
                 "freq": 20.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        # Pluriels irreguliers
        "cheval": [{"ortho": "cheval", "cgram": "NOM", "phone": "\u0283\u0259val",
                    "freq": 30.0, "genre": "m", "nombre": "s"}],
        "chevaux": [{"ortho": "chevaux", "cgram": "NOM", "phone": "\u0283\u0259vo",
                     "freq": 15.0, "genre": "m", "nombre": "p"}],
        "journal": [{"ortho": "journal", "cgram": "NOM", "phone": "\u0292u\u0281nal",
                     "freq": 25.0, "genre": "m", "nombre": "s"}],
        "journaux": [{"ortho": "journaux", "cgram": "NOM", "phone": "\u0292u\u0281no",
                      "freq": 12.0, "genre": "m", "nombre": "p"}],
        "gâteau": [{"ortho": "gâteau", "cgram": "NOM", "phone": "gato",
                    "freq": 10.0, "genre": "m", "nombre": "s"}],
        "gâteaux": [{"ortho": "gâteaux", "cgram": "NOM", "phone": "gato",
                     "freq": 5.0, "genre": "m", "nombre": "p"}],
        # Homophones
        "à": [{"ortho": "à", "cgram": "PRE", "phone": "a",
               "freq": 500.0}],
        "où": [{"ortho": "où", "cgram": "PRO:rel", "phone": "u",
                "freq": 100.0}],
        "on": [{"ortho": "on", "cgram": "PRO:ind", "phone": "\u0254\u0303",
                "freq": 300.0}],
        "se": [{"ortho": "se", "cgram": "PRO:per", "phone": "s\u0259",
                "freq": 200.0}],
        "là": [{"ortho": "là", "cgram": "ADV", "phone": "la",
                "freq": 80.0}],
        # Feminisation -x
        "roux": [{"ortho": "roux", "cgram": "ADJ", "phone": "\u0281u",
                  "freq": 10.0, "genre": "m", "nombre": "s"}],
        "rousse": [{"ortho": "rousse", "cgram": "ADJ", "phone": "\u0281us",
                    "freq": 8.0, "genre": "f", "nombre": "s"}],
        "doux": [{"ortho": "doux", "cgram": "ADJ", "phone": "du",
                  "freq": 15.0, "genre": "m", "nombre": "s"}],
        "douce": [{"ortho": "douce", "cgram": "ADJ", "phone": "dus",
                   "freq": 12.0, "genre": "f", "nombre": "s"}],
        "faux": [{"ortho": "faux", "cgram": "ADJ", "phone": "fo",
                  "freq": 20.0, "genre": "m", "nombre": "s"}],
        "fausse": [{"ortho": "fausse", "cgram": "ADJ", "phone": "fos",
                    "freq": 15.0, "genre": "f", "nombre": "s"}],
        # Verbes irreguliers supplementaires
        "court": [{"ortho": "court", "cgram": "VER", "phone": "ku\u0281",
                   "freq": 10.0, "personne": "3", "nombre": "s"}],
        "courent": [{"ortho": "courent", "cgram": "VER", "phone": "ku\u0281",
                     "freq": 5.0, "personne": "3", "nombre": "p"}],
        "sort": [{"ortho": "sort", "cgram": "VER", "phone": "s\u0254\u0281",
                  "freq": 10.0, "personne": "3", "nombre": "s"}],
        "sortent": [{"ortho": "sortent", "cgram": "VER", "phone": "s\u0254\u0281t",
                     "freq": 5.0, "personne": "3", "nombre": "p"}],
        # Féminisation -eux/-euse
        "heureux": [{"ortho": "heureux", "cgram": "ADJ", "phone": "\u00f8\u0281\u00f8",
                     "freq": 20.0, "genre": "m", "nombre": "s"}],
        "heureuse": [{"ortho": "heureuse", "cgram": "ADJ", "phone": "\u00f8\u0281\u00f8z",
                      "freq": 15.0, "genre": "f", "nombre": "s"}],
        # Noms pour tests genre
        "homme": [{"ortho": "homme", "cgram": "NOM", "phone": "\u0254m",
                   "freq": 200.0, "genre": "m", "nombre": "s"}],
        "vent": [{"ortho": "vent", "cgram": "NOM", "phone": "v\u0251\u0303",
                  "freq": 25.0, "genre": "m", "nombre": "s"}],
        "note": [{"ortho": "note", "cgram": "NOM", "phone": "n\u0254t",
                  "freq": 20.0, "genre": "f", "nombre": "s"}],
        # Homophones supplémentaires
        "ou": [{"ortho": "ou", "cgram": "CON", "phone": "u",
                "freq": 200.0}],
        # --- PP feminins/pluriels (pour PP_ETRE) ---
        "allé": [{"ortho": "allé", "cgram": "VER", "phone": "ale",
                  "freq": 20.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "allée": [{"ortho": "allée", "cgram": "VER", "phone": "ale",
                   "freq": 15.0, "mode": "participe", "genre": "f", "nombre": "s"}],
        "allés": [{"ortho": "allés", "cgram": "VER", "phone": "ale",
                   "freq": 10.0, "mode": "participe", "genre": "m", "nombre": "p"}],
        "allées": [{"ortho": "allées", "cgram": "VER", "phone": "ale",
                    "freq": 8.0, "mode": "participe", "genre": "f", "nombre": "p"}],
        "arrivé": [{"ortho": "arrivé", "cgram": "VER", "phone": "aʁive",
                    "freq": 15.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "arrivée": [{"ortho": "arrivée", "cgram": "VER", "phone": "aʁive",
                     "freq": 12.0, "mode": "participe", "genre": "f", "nombre": "s"}],
        "arrivés": [{"ortho": "arrivés", "cgram": "VER", "phone": "aʁive",
                     "freq": 8.0, "mode": "participe", "genre": "m", "nombre": "p"}],
        "arrivées": [{"ortho": "arrivées", "cgram": "VER", "phone": "aʁive",
                      "freq": 5.0, "mode": "participe", "genre": "f", "nombre": "p"}],
        "parti": [{"ortho": "parti", "cgram": "VER", "phone": "paʁti",
                   "freq": 15.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "partie": [{"ortho": "partie", "cgram": "VER", "phone": "paʁti",
                    "freq": 12.0, "mode": "participe", "genre": "f", "nombre": "s"}],
        "partis": [{"ortho": "partis", "cgram": "VER", "phone": "paʁti",
                    "freq": 8.0, "mode": "participe", "genre": "m", "nombre": "p"}],
        "parties": [{"ortho": "parties", "cgram": "VER", "phone": "paʁti",
                     "freq": 5.0, "mode": "participe", "genre": "f", "nombre": "p"}],
        "tombé": [{"ortho": "tombé", "cgram": "VER", "phone": "tɔ̃be",
                   "freq": 15.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "tombée": [{"ortho": "tombée", "cgram": "VER", "phone": "tɔ̃be",
                    "freq": 12.0, "mode": "participe", "genre": "f", "nombre": "s"}],
        "tombés": [{"ortho": "tombés", "cgram": "VER", "phone": "tɔ̃be",
                    "freq": 8.0, "mode": "participe", "genre": "m", "nombre": "p"}],
        "tombées": [{"ortho": "tombées", "cgram": "VER", "phone": "tɔ̃be",
                     "freq": 5.0, "mode": "participe", "genre": "f", "nombre": "p"}],
        "venu": [{"ortho": "venu", "cgram": "VER", "phone": "vəny",
                  "freq": 15.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        "venue": [{"ortho": "venue", "cgram": "VER", "phone": "vəny",
                   "freq": 12.0, "mode": "participe", "genre": "f", "nombre": "s"}],
        "venus": [{"ortho": "venus", "cgram": "VER", "phone": "vəny",
                   "freq": 8.0, "mode": "participe", "genre": "m", "nombre": "p"}],
        "venues": [{"ortho": "venues", "cgram": "VER", "phone": "vəny",
                    "freq": 5.0, "mode": "participe", "genre": "f", "nombre": "p"}],
        # --- Formes imparfait/futur (pour CONJ_IMP/CONJ_FUT) ---
        "mangeais": [{"ortho": "mangeais", "cgram": "VER", "phone": "mɑ̃ʒɛ",
                      "freq": 5.0, "personne": "1", "nombre": "s"}],
        "mangeait": [{"ortho": "mangeait", "cgram": "VER", "phone": "mɑ̃ʒɛ",
                      "freq": 8.0, "personne": "3", "nombre": "s"}],
        "mangions": [{"ortho": "mangions", "cgram": "VER", "phone": "mɑ̃ʒjɔ̃",
                      "freq": 3.0, "personne": "1", "nombre": "p"}],
        "mangiez": [{"ortho": "mangiez", "cgram": "VER", "phone": "mɑ̃ʒje",
                     "freq": 3.0, "personne": "2", "nombre": "p"}],
        "mangeaient": [{"ortho": "mangeaient", "cgram": "VER", "phone": "mɑ̃ʒɛ",
                        "freq": 5.0, "personne": "3", "nombre": "p"}],
        "mangera": [{"ortho": "mangera", "cgram": "VER", "phone": "mɑ̃ʒʁa",
                     "freq": 5.0, "personne": "3", "nombre": "s"}],
        "mangerai": [{"ortho": "mangerai", "cgram": "VER", "phone": "mɑ̃ʒʁe",
                      "freq": 3.0, "personne": "1", "nombre": "s"}],
        "mangeras": [{"ortho": "mangeras", "cgram": "VER", "phone": "mɑ̃ʒʁa",
                      "freq": 3.0, "personne": "2", "nombre": "s"}],
        "mangerons": [{"ortho": "mangerons", "cgram": "VER", "phone": "mɑ̃ʒʁɔ̃",
                       "freq": 3.0, "personne": "1", "nombre": "p"}],
        "mangerez": [{"ortho": "mangerez", "cgram": "VER", "phone": "mɑ̃ʒʁe",
                      "freq": 3.0, "personne": "2", "nombre": "p"}],
        "mangeront": [{"ortho": "mangeront", "cgram": "VER", "phone": "mɑ̃ʒʁɔ̃",
                       "freq": 3.0, "personne": "3", "nombre": "p"}],
        "finira": [{"ortho": "finira", "cgram": "VER", "phone": "finiʁa",
                    "freq": 5.0, "personne": "3", "nombre": "s"}],
        "finirai": [{"ortho": "finirai", "cgram": "VER", "phone": "finiʁe",
                     "freq": 3.0, "personne": "1", "nombre": "s"}],
        "finiras": [{"ortho": "finiras", "cgram": "VER", "phone": "finiʁa",
                     "freq": 3.0, "personne": "2", "nombre": "s"}],
        "finirons": [{"ortho": "finirons", "cgram": "VER", "phone": "finiʁɔ̃",
                      "freq": 3.0, "personne": "1", "nombre": "p"}],
        "finirez": [{"ortho": "finirez", "cgram": "VER", "phone": "finiʁe",
                     "freq": 3.0, "personne": "2", "nombre": "p"}],
        "finiront": [{"ortho": "finiront", "cgram": "VER", "phone": "finiʁɔ̃",
                      "freq": 3.0, "personne": "3", "nombre": "p"}],
        "finissais": [{"ortho": "finissais", "cgram": "VER", "phone": "finisɛ",
                       "freq": 3.0, "personne": "1", "nombre": "s"}],
        "finissait": [{"ortho": "finissait", "cgram": "VER", "phone": "finisɛ",
                       "freq": 5.0, "personne": "3", "nombre": "s"}],
        "finissaient": [{"ortho": "finissaient", "cgram": "VER", "phone": "finisɛ",
                         "freq": 3.0, "personne": "3", "nombre": "p"}],
        "dormais": [{"ortho": "dormais", "cgram": "VER", "phone": "dɔʁmɛ",
                     "freq": 3.0, "personne": "1", "nombre": "s"}],
        "dormait": [{"ortho": "dormait", "cgram": "VER", "phone": "dɔʁmɛ",
                     "freq": 5.0, "personne": "3", "nombre": "s"}],
        "dormaient": [{"ortho": "dormaient", "cgram": "VER", "phone": "dɔʁmɛ",
                       "freq": 3.0, "personne": "3", "nombre": "p"}],
        "parlait": [{"ortho": "parlait", "cgram": "VER", "phone": "paʁlɛ",
                     "freq": 5.0, "personne": "3", "nombre": "s"}],
        "parlais": [{"ortho": "parlais", "cgram": "VER", "phone": "paʁlɛ",
                     "freq": 3.0, "personne": "1", "nombre": "s"}],
        "parlaient": [{"ortho": "parlaient", "cgram": "VER", "phone": "paʁlɛ",
                       "freq": 3.0, "personne": "3", "nombre": "p"}],
        "chantera": [{"ortho": "chantera", "cgram": "VER", "phone": "ʃɑ̃tʁa",
                      "freq": 5.0, "personne": "3", "nombre": "s"}],
        "chanterai": [{"ortho": "chanterai", "cgram": "VER", "phone": "ʃɑ̃tʁe",
                       "freq": 3.0, "personne": "1", "nombre": "s"}],
        "chanteras": [{"ortho": "chanteras", "cgram": "VER", "phone": "ʃɑ̃tʁa",
                       "freq": 3.0, "personne": "2", "nombre": "s"}],
        "chanterons": [{"ortho": "chanterons", "cgram": "VER", "phone": "ʃɑ̃tʁɔ̃",
                        "freq": 3.0, "personne": "1", "nombre": "p"}],
        "chanterez": [{"ortho": "chanterez", "cgram": "VER", "phone": "ʃɑ̃tʁe",
                       "freq": 3.0, "personne": "2", "nombre": "p"}],
        "chanteront": [{"ortho": "chanteront", "cgram": "VER", "phone": "ʃɑ̃tʁɔ̃",
                        "freq": 3.0, "personne": "3", "nombre": "p"}],
        "parleront": [{"ortho": "parleront", "cgram": "VER", "phone": "paʁlʁɔ̃",
                       "freq": 3.0, "personne": "3", "nombre": "p"}],
        "parlerai": [{"ortho": "parlerai", "cgram": "VER", "phone": "paʁlʁe",
                      "freq": 3.0, "personne": "1", "nombre": "s"}],
        "parlera": [{"ortho": "parlera", "cgram": "VER", "phone": "paʁlʁa",
                     "freq": 5.0, "personne": "3", "nombre": "s"}],
        "parlerons": [{"ortho": "parlerons", "cgram": "VER", "phone": "paʁlʁɔ̃",
                       "freq": 3.0, "personne": "1", "nombre": "p"}],
        # --- Formes attribut (pour ATTR) ---
        "contente": [{"ortho": "contente", "cgram": "ADJ", "phone": "kɔ̃tɑ̃t",
                      "freq": 15.0, "genre": "f", "nombre": "s"}],
        "contentes": [{"ortho": "contentes", "cgram": "ADJ", "phone": "kɔ̃tɑ̃t",
                       "freq": 8.0, "genre": "f", "nombre": "p"}],
        "beau": [{"ortho": "beau", "cgram": "ADJ", "phone": "bo",
                  "freq": 30.0, "genre": "m", "nombre": "s"}],
        "bel": [{"ortho": "bel", "cgram": "ADJ", "phone": "bɛl",
                 "freq": 10.0, "genre": "m", "nombre": "s"}],
        "beaux": [{"ortho": "beaux", "cgram": "ADJ", "phone": "bo",
                   "freq": 15.0, "genre": "m", "nombre": "p"}],
        # --- Homophones leur/leurs, ca/sa ---
        "leur": [{"ortho": "leur", "cgram": "DET", "phone": "lœʁ",
                  "freq": 100.0, "nombre": "s"}],
        "leurs": [{"ortho": "leurs", "cgram": "DET", "phone": "lœʁ",
                   "freq": 80.0, "nombre": "p"}],
        "ça": [{"ortho": "ça", "cgram": "PRO:dem", "phone": "sa",
                "freq": 100.0}],
        "sa": [{"ortho": "sa", "cgram": "ADJ:pos", "phone": "sa",
                "freq": 120.0, "genre": "f", "nombre": "s"}],
        # Infinitifs supplementaires pour -er/-e apres aller
        "aller": [{"ortho": "aller", "cgram": "VER", "phone": "ale",
                   "freq": 50.0, "mode": "inf"}],
        "arriver": [{"ortho": "arriver", "cgram": "VER", "phone": "aʁive",
                     "freq": 20.0, "mode": "inf"}],
        "partir": [{"ortho": "partir", "cgram": "VER", "phone": "paʁtiʁ",
                    "freq": 20.0, "mode": "inf"}],
        "tomber": [{"ortho": "tomber", "cgram": "VER", "phone": "tɔ̃be",
                    "freq": 15.0, "mode": "inf"}],
        "venir": [{"ortho": "venir", "cgram": "VER", "phone": "vəniʁ",
                   "freq": 20.0, "mode": "inf"}],
        # Verbe 'parle' (forme conjuguee)
        "parle": [{"ortho": "parle", "cgram": "VER", "phone": "paʁl",
                   "freq": 15.0, "personne": "3", "nombre": "s"}],
        "parlent": [{"ortho": "parlent", "cgram": "VER", "phone": "paʁl",
                     "freq": 8.0, "personne": "3", "nombre": "p"}],
        # été (PP etre)
        "été": [{"ortho": "été", "cgram": "VER", "phone": "ete",
                 "freq": 20.0, "mode": "participe", "genre": "m", "nombre": "s"}],
        # Supplementaires pour corpus evaluation
        "chanson": [{"ortho": "chanson", "cgram": "NOM", "phone": "ʃɑ̃sɔ̃",
                     "freq": 20.0, "genre": "f", "nombre": "s"}],
        "chansons": [{"ortho": "chansons", "cgram": "NOM", "phone": "ʃɑ̃sɔ̃",
                      "freq": 10.0, "genre": "f", "nombre": "p"}],
        "rouge": [{"ortho": "rouge", "cgram": "ADJ", "phone": "ʁuʒ",
                   "freq": 25.0, "genre": "m", "nombre": "s"},
                  {"ortho": "rouge", "cgram": "ADJ", "phone": "ʁuʒ",
                   "freq": 25.0, "genre": "f", "nombre": "s"}],
        "rouges": [{"ortho": "rouges", "cgram": "ADJ", "phone": "ʁuʒ",
                    "freq": 10.0, "genre": "m", "nombre": "p"},
                   {"ortho": "rouges", "cgram": "ADJ", "phone": "ʁuʒ",
                    "freq": 10.0, "genre": "f", "nombre": "p"}],
        "regarde": [{"ortho": "regarde", "cgram": "VER", "phone": "ʁəɡaʁd",
                     "freq": 15.0, "personne": "3", "nombre": "s"}],
        "regardent": [{"ortho": "regardent", "cgram": "VER", "phone": "ʁəɡaʁd",
                       "freq": 8.0, "personne": "3", "nombre": "p"}],
        "donne": [{"ortho": "donne", "cgram": "VER", "phone": "dɔn",
                   "freq": 15.0, "personne": "3", "nombre": "s"}],
        "donnent": [{"ortho": "donnent", "cgram": "VER", "phone": "dɔn",
                     "freq": 8.0, "personne": "3", "nombre": "p"}],
        "fleur": [{"ortho": "fleur", "cgram": "NOM", "phone": "flœʁ",
                   "freq": 20.0, "genre": "f", "nombre": "s"}],
        "fleurs": [{"ortho": "fleurs", "cgram": "NOM", "phone": "flœʁ",
                    "freq": 15.0, "genre": "f", "nombre": "p"}],
        "garçon": [{"ortho": "garçon", "cgram": "NOM", "phone": "ɡaʁsɔ̃",
                    "freq": 30.0, "genre": "m", "nombre": "s"}],
        "garçons": [{"ortho": "garçons", "cgram": "NOM", "phone": "ɡaʁsɔ̃",
                     "freq": 15.0, "genre": "m", "nombre": "p"}],
        "ami": [{"ortho": "ami", "cgram": "NOM", "phone": "ami",
                 "freq": 25.0, "genre": "m", "nombre": "s"}],
        "amis": [{"ortho": "amis", "cgram": "NOM", "phone": "ami",
                  "freq": 15.0, "genre": "m", "nombre": "p"}],
        "oiseau": [{"ortho": "oiseau", "cgram": "NOM", "phone": "wazo",
                    "freq": 15.0, "genre": "m", "nombre": "s"}],
        "oiseaux": [{"ortho": "oiseaux", "cgram": "NOM", "phone": "wazo",
                     "freq": 10.0, "genre": "m", "nombre": "p"}],
        "jolie": [{"ortho": "jolie", "cgram": "ADJ", "phone": "ʒɔli",
                   "freq": 15.0, "genre": "f", "nombre": "s"}],
        "jolies": [{"ortho": "jolies", "cgram": "ADJ", "phone": "ʒɔli",
                    "freq": 8.0, "genre": "f", "nombre": "p"}],
        "lit": [{"ortho": "lit", "cgram": "NOM", "phone": "li",
                 "freq": 20.0, "genre": "m", "nombre": "s"}],
        "table": [{"ortho": "table", "cgram": "NOM", "phone": "tabl",
                   "freq": 25.0, "genre": "f", "nombre": "s"}],
        "cour": [{"ortho": "cour", "cgram": "NOM", "phone": "kuʁ",
                  "freq": 15.0, "genre": "f", "nombre": "s"}],
        # Accent variants (Axe 1)
        "école": [{"ortho": "école", "cgram": "NOM", "phone": "ekɔl",
                    "freq": 2.0, "genre": "f", "nombre": "s"}],
        "mère": [{"ortho": "mère", "cgram": "NOM", "phone": "mɛʁ",
                   "freq": 3.0, "genre": "f", "nombre": "s"}],
        "fatigué": [{"ortho": "fatigué", "cgram": "ADJ", "phone": "fatiɡe",
                     "freq": 1.5, "genre": "m", "nombre": "s"}],
        # Double consonants (Axe 2)
        "apportons": [{"ortho": "apportons", "cgram": "VER", "phone": "apɔʁtɔ̃",
                       "freq": 2.0, "personne": "1", "nombre": "p"}],
        "excellentes": [{"ortho": "excellentes", "cgram": "ADJ", "phone": "ɛksɛlɑ̃t",
                         "freq": 2.0, "genre": "f", "nombre": "p"}],
        "difficile": [{"ortho": "difficile", "cgram": "ADJ", "phone": "difisil",
                       "freq": 15.0, "genre": "m", "nombre": "s"}],
        "ballon": [{"ortho": "ballon", "cgram": "NOM", "phone": "balɔ̃",
                    "freq": 10.0, "genre": "m", "nombre": "s"}],
        # Fusion (Axe 3)
        "beaucoup": [{"ortho": "beaucoup", "cgram": "ADV", "phone": "boku",
                      "freq": 80.0}],
        "ensemble": [{"ortho": "ensemble", "cgram": "ADV", "phone": "ɑ̃sɑ̃bl",
                      "freq": 50.0}],
        "toujours": [{"ortho": "toujours", "cgram": "ADV", "phone": "tuʒuʁ",
                      "freq": 60.0}],
        "peut-être": [{"ortho": "peut-être", "cgram": "ADV", "phone": "pøtɛtʁ",
                        "freq": 80.0}],
        "peut": [{"ortho": "peut", "cgram": "VER", "phone": "pø",
                  "freq": 100.0, "personne": "3", "nombre": "s"}],
        "être": [{"ortho": "être", "cgram": "AUX", "phone": "ɛtʁ",
                  "freq": 200.0, "mode": "inf"}],
        # Elision (Axe 4)
        "que": [{"ortho": "que", "cgram": "CON", "phone": "kə",
                 "freq": 300.0}],
        "me": [{"ortho": "me", "cgram": "PRO:per", "phone": "mə",
                "freq": 200.0}],
        "te": [{"ortho": "te", "cgram": "PRO:per", "phone": "tə",
                "freq": 150.0}],
        # Conjugaison tronquee (Axe 6)
        "dansions": [{"ortho": "dansions", "cgram": "VER", "phone": "dɑ̃sjɔ̃",
                      "freq": 2.0, "personne": "1", "nombre": "p"}],
        # Formes pour tests sujets nominaux pluriels (CONJ)
        "promenaient": [{"ortho": "promenaient", "cgram": "VER", "phone": "pʁɔmnɛ",
                         "freq": 3.0, "personne": "3", "nombre": "p"}],
        "promenais": [{"ortho": "promenais", "cgram": "VER", "phone": "pʁɔmnɛ",
                       "freq": 3.0, "personne": "1", "nombre": "s"}],
        "passeront": [{"ortho": "passeront", "cgram": "VER", "phone": "pasʁɔ̃",
                       "freq": 3.0, "personne": "3", "nombre": "p"}],
        "passerons": [{"ortho": "passerons", "cgram": "VER", "phone": "pasʁɔ̃",
                       "freq": 3.0, "personne": "1", "nombre": "p"}],
        "partirons": [{"ortho": "partirons", "cgram": "VER", "phone": "paʁtiʁɔ̃",
                       "freq": 3.0, "personne": "1", "nombre": "p"}],
        "habite": [{"ortho": "habite", "cgram": "VER", "phone": "abit",
                    "freq": 10.0, "personne": "3", "nombre": "s"}],
        "sais": [{"ortho": "sais", "cgram": "VER", "phone": "sɛ",
                  "freq": 30.0, "personne": "1", "nombre": "s"}],
        "gens": [{"ortho": "gens", "cgram": "NOM", "phone": "ʒɑ̃",
                  "freq": 25.0, "genre": "m", "nombre": "p"}],
        # Accent disambiguation: forme sans accent (rare) vs avec accent (frequente)
        "tres": [{"ortho": "tres", "cgram": "ADV", "phone": "t\u0281\u025b",
                  "freq": 1.0}],
        "très": [{"ortho": "très", "cgram": "ADV", "phone": "t\u0281\u025b",
                   "freq": 500.0}],
        "foret": [{"ortho": "foret", "cgram": "NOM", "phone": "f\u0254\u0281\u025b",
                   "freq": 1.0, "genre": "f", "nombre": "s"}],
        "forêt": [{"ortho": "forêt", "cgram": "NOM", "phone": "f\u0254\u0281\u025b",
                    "freq": 50.0, "genre": "f", "nombre": "s"}],
        "diner": [{"ortho": "diner", "cgram": "NOM", "phone": "dine",
                   "freq": 2.0, "genre": "m", "nombre": "s"}],
        "dîner": [{"ortho": "dîner", "cgram": "NOM", "phone": "dine",
                    "freq": 40.0, "genre": "m", "nombre": "s"}],
        # Sigles
        "onu": [{"ortho": "onu", "cgram": "SIGLE", "phone": "ɔny",
                 "freq": 5.0}],
        "otan": [{"ortho": "otan", "cgram": "SIGLE", "phone": "ɔtɑ̃",
                  "freq": 3.0}],
        # Noms propres
        "mozart": [{"ortho": "mozart", "cgram": "NOM PROPRE", "phone": "mɔzaʁ",
                    "freq": 10.0, "genre": "m", "nombre": "s"}],
        "berlin": [{"ortho": "berlin", "cgram": "NOM PROPRE", "phone": "bɛʁlɛ̃",
                    "freq": 8.0, "genre": "m", "nombre": "s"}],
    }


def _CONJUGAISONS_DEFAUT() -> dict[str, dict]:
    """Tables de conjugaison minimales pour les tests."""
    return {
        "manger": {"indicatif": {
            "présent": {"1s": "mange", "2s": "manges", "3s": "mange",
                        "1p": "mangeons", "2p": "mangez", "3p": "mangent"},
            "imparfait": {"1s": "mangeais", "2s": "mangeais", "3s": "mangeait",
                          "1p": "mangions", "2p": "mangiez", "3p": "mangeaient"},
            "futur": {"1s": "mangerai", "2s": "mangeras", "3s": "mangera",
                      "1p": "mangerons", "2p": "mangerez", "3p": "mangeront"},
        }},
        "finir": {"indicatif": {
            "présent": {"1s": "finis", "2s": "finis", "3s": "finit",
                        "1p": "finissons", "2p": "finissez", "3p": "finissent"},
            "imparfait": {"1s": "finissais", "2s": "finissais", "3s": "finissait",
                          "1p": "finissions", "2p": "finissiez", "3p": "finissaient"},
            "futur": {"1s": "finirai", "2s": "finiras", "3s": "finira",
                      "1p": "finirons", "2p": "finirez", "3p": "finiront"},
        }},
        "dormir": {"indicatif": {
            "présent": {"1s": "dors", "2s": "dors", "3s": "dort",
                        "1p": "dormons", "2p": "dormez", "3p": "dorment"},
            "imparfait": {"1s": "dormais", "2s": "dormais", "3s": "dormait",
                          "1p": "dormions", "2p": "dormiez", "3p": "dormaient"},
        }},
        "chanter": {"indicatif": {
            "présent": {"1s": "chante", "2s": "chantes", "3s": "chante",
                        "1p": "chantons", "2p": "chantez", "3p": "chantent"},
            "imparfait": {"1s": "chantais", "2s": "chantais", "3s": "chantait",
                          "1p": "chantions", "2p": "chantiez", "3p": "chantaient"},
            "futur": {"1s": "chanterai", "2s": "chanteras", "3s": "chantera",
                      "1p": "chanterons", "2p": "chanterez", "3p": "chanteront"},
        }},
        "parler": {"indicatif": {
            "présent": {"1s": "parle", "2s": "parles", "3s": "parle",
                        "1p": "parlons", "2p": "parlez", "3p": "parlent"},
            "imparfait": {"1s": "parlais", "2s": "parlais", "3s": "parlait",
                          "1p": "parlions", "2p": "parliez", "3p": "parlaient"},
            "futur": {"1s": "parlerai", "2s": "parleras", "3s": "parlera",
                      "1p": "parlerons", "2p": "parlerez", "3p": "parleront"},
        }},
        "promener": {"indicatif": {
            "imparfait": {"1s": "promenais", "2s": "promenais", "3s": "promenait",
                          "1p": "promenions", "2p": "promeniez", "3p": "promenaient"},
        }},
    }


@pytest.fixture
def mock_lexique():
    """Fixture MockLexique avec donnees par defaut."""
    return MockLexique()
